### ISSUE TITLE
Metric request error

### ISSUE THREAD

**Issue by botzill** [PhracturedBlue/mongodb-grafana-backend#2]
I did install this plugin on latest grafana and I get this error:

```
Metric request error
```

Any ideas?

**Comment by tiger-seo** [comment]
maybe this logs could help:
```
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="looking up token" logger=auth unhashed=1bc2eedfbcdbbddcc65b264e08114cbb hashed=63033338cca5814921545d7b2c618d08bf2bed7b3f1c672b891e0a2ac9a35a7f
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="token needs rotation" logger=auth tokenId=1 authTokenSeen=true rotatedAt=2019-08-09T11:53:22+0000
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="auth token rotated" logger=auth affected=1 auth_token_id=1 userId=1
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=info msg="new token" logger=context unhashed token=0ceb77d12f2b9ca8957f651439a5cf4d
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="2019-08-09T13:18:19.506Z [DEBUG] mongodb-grafana: Query: datasource=mongodb TimeRange=\"fromRaw:\"NaN\" toRaw:\"1565356699469\" toEpochMs:1565356699469 \"" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="2019-08-09T13:18:19.506Z [DEBUG] mongodb-grafana: Request: timeRange:<fromRaw:\"NaN\" toRaw:\"1565356699469\" toEpochMs:1565356699469 > datasource:<id:1 orgId:1 name:\"mongodb\" type:\"grafana-mongodb-backend-datasource\" url:\"mongodb://mongodb:27017\" jsonData:\"{\\\"mongodb_db\\\":\\\"local\\\"}\" > queries:<refId:\"search\" maxDataPoints:100 intervalMs:1000 modelJson:\"{\\\"datasourceId\\\":1,\\\"queryType\\\":\\\"metricsQuery\\\",\\\"refId\\\":\\\"search\\\",\\\"target\\\":\\\"ping\\\"}\" >" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="2019-08-09T13:18:19.507Z [DEBUG] mongodb-grafana: Got Metrics Target: search" logger=plugins plugin-id=grafana-mongodb-backend-datasource grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="2019-08-09T13:18:19.507Z [DEBUG] mongodb-grafana: QueryString: : {\"datasourceId\":1,\"queryType\":\"metricsQuery\",\"refId\":\"search\",\"target\":\"ping\"}=<unknown>" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa0e094]" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg= logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="goroutine 12 [running]:" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="main.(*MongoDBDatasource).executeMetricsQuery(0xc00001e0f0, 0xceeb40, 0xc0001b0c90, 0xc0001d0460, 0x0, 0x0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/pkg/datasource.go:109 +0xe34" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="main.(*MongoDBDatasource).Query(0xc00001e0f0, 0xceeb40, 0xc0001b0c90, 0xc0001d0460, 0xab2fc0, 0xac0f00, 0xce6d20)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/pkg/datasource.go:43 +0x6e7" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="github.com/PhracturedBlue/mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource.(*GRPCServer).Query(0xc00001e170, 0xceeb40, 0xc0001b0c90, 0xc0001d0460, 0xc00001e170, 0xc0001b0c00, 0xac0f20)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = transport is closing"
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=172.20.0.1 time_ms=34 size=102 referer=http://localhost:3000/datasources/edit/1/
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource/service.go:41 +0x51" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="github.com/PhracturedBlue/mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource._DatasourcePlugin_Query_Handler(0xab2fc0, 0xc00001e170, 0xceeb40, 0xc0001b0c90, 0xc0001dc2a0, 0x0, 0x0, 0x0, 0x0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource/datasource.pb.go:805 +0x23e" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e0000, 0xcf2280, 0xc000218000, 0xc0001de0f0, 0xc0001b0690, 0x11b6860, 0x0, 0x0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:1011 +0x4cd" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="plugin process exited" logger=plugins plugin-id=grafana-mongodb-backend-datasource path=/var/lib/grafana/plugins/mongodb-grafana-backend/dist/mongodb-be-plugin_linux_amd64
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001e0000, 0xcf2280, 0xc000218000, 0xc0001de0f0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:1249 +0x1311" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000281b0, 0xc0001e0000, 0xcf2280, 0xc000218000, 0xc0001de0f0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:680 +0x9f" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="created by github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="\t/home/travis/gopath/src/github.com/PhracturedBlue/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:678 +0xa1" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="starting plugin" logger=plugins plugin-id=grafana-mongodb-backend-datasource path=/var/lib/grafana/plugins/mongodb-grafana-backend/dist/mongodb-be-plugin_linux_amd64 args=[/var/lib/grafana/plugins/mongodb-grafana-backend/dist/mongodb-be-plugin_linux_amd64]
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="waiting for RPC address" logger=plugins plugin-id=grafana-mongodb-backend-datasource path=/var/lib/grafana/plugins/mongodb-grafana-backend/dist/mongodb-be-plugin_linux_amd64
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="2019-08-09T13:18:19.724Z [DEBUG] mongodb-grafana: Running GRPC server" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="plugin address" logger=plugins plugin-id=grafana-mongodb-backend-datasource address=/tmp/plugin418314699 network=unix timestamp=2019-08-09T13:18:19.725Z
grafana_1  | t=2019-08-09T13:18:19+0000 lvl=dbug msg="Spawning new sub process" logger=plugins plugin-id=grafana-mongodb-backend-datasource name=MongoDB-BE id=grafana-mongodb-backend-datasource
```

**Comment by tiger-seo** [comment]
also, for me this error happens only when clicking Test in the Settings of MongoDB BE data source

**Comment by tiger-seo** [comment]
seems there is a problem with `metricsQuery` type of requests

**Comment by rplevka** [comment]
I'm also having this issue.
~~I can only see `lvl=error` as I have no clue how to set different log level with docker-compose.~~

```

grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="2019-08-15T09:08:50.301Z [DEBUG] mongodb-grafana: Query: datasource=reportportal TimeRange=\"fromRaw:\"NaN\" toRaw:\"1565860130295\" toEpochMs:1565860130295 \"" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="2019-08-15T09:08:50.301Z [DEBUG] mongodb-grafana: Request: timeRange:<fromRaw:\"NaN\" toRaw:\"1565860130295\" toEpochMs:1565860130295 > datasource:<id:2 orgId:1 name:\"reportportal\" type:\"grafana-mongodb-backend-datasource\" jsonData:\"{\\\"mongodb_db\\\":\\\"reportportal\\\",\\\"mongodb_url\\\":\\\"mongodb://mongodb:27017\\\",\\\"stages\\\":[]}\" > queries:<refId:\"search\" maxDataPoints:100 intervalMs:1000 modelJson:\"{\\\"datasourceId\\\":2,\\\"queryType\\\":\\\"metricsQuery\\\",\\\"refId\\\":\\\"search\\\",\\\"target\\\":\\\"ping\\\"}\" > " logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="2019-08-15T09:08:50.301Z [DEBUG] mongodb-grafana: Got Metrics Target: search" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="2019-08-15T09:08:50.301Z [DEBUG] mongodb-grafana: QueryString: : {\"datasourceId\":2,\"queryType\":\"metricsQuery\",\"refId\":\"search\",\"target\":\"ping\"}=<unknown>" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9dbd71]" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg= logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="goroutine 34 [running]:" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="main.(*MongoDBDatasource).executeMetricsQuery(0xc0001a06f0, 0xca4900, 0xc00023a1b0, 0xc0002420f0, 0x0, 0x0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/pkg/datasource.go:109 +0xe31" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="main.(*MongoDBDatasource).Query(0xc0001a06f0, 0xca4900, 0xc00023a1b0, 0xc0002420f0, 0xa815a0, 0xa8e200, 0xc9d9a0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/pkg/datasource.go:43 +0x6e7" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource.(*GRPCServer).Query(0xc0001a0770, 0xca4900, 0xc00023a1b0, 0xc0002420f0, 0xc0001a0770, 0xc00023a120, 0xa8e220)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource/service.go:41 +0x51" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource._DatasourcePlugin_Query_Handler(0xa815a0, 0xc0001a0770, 0xca4900, 0xc00023a1b0, 0xc000244070, 0x0, 0x0, 0x0, 0x0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/vendor/github.com/grafana/grafana_plugin_model/go/datasource/datasource.pb.go:805 +0x23e" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d0000, 0xca78c0, 0xc000214000, 0xc000250000, 0xc00014bd40, 0x114f050, 0x0, 0x0, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:1011 +0x4cd" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001d0000, 0xca78c0, 0xc000214000, 0xc000250000, 0x0)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:1249 +0x1311" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001be050, 0xc0001d0000, 0xca78c0, 0xc000214000, 0xc000250000)" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:680 +0x9f" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="created by mongodb-grafana-backend/vendor/google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="\t/home/rplevka/go/src/mongodb-grafana-backend/vendor/google.golang.org/grpc/server.go:678 +0xa1" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = transport is closing"
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.1.1.1 time_ms=6 size=34 referer=http://reportportal.foo.com:3000/datasources/edit/2/
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="plugin process exited" logger=plugins plugin-id=grafana-mongodb-backend-datasource path=/var/lib/grafana/plugins/mongodb-grafana-backend/dist/mongodb-be-plugin_linux_amd64 pid=69 error="exit status 2"
```

I tihnk the culprit would be:
```
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins plugin-id=grafana-mongodb-backend-datasource
grafana_1        | t=2019-08-15T09:08:50+0000 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9dbd71]" logger=plugins plugin-id=grafana-mongodb-backend-datasource
```
Which I can also see in @tiger-seo's pasted output

**Comment by guvenim** [comment]
I am having the same issue as well

**Comment by timstallinger** [comment]
same, did anybody figure something out yet? JamesOsgood's repo gives me an HTTP Error, this gives me Metric request Error and maxbr's docker gives me a bad gateway Error. It just doesnt want to work with MongoDB for me

**Comment by botzill** [comment]
Hi. Any updates?

**Comment by BoKKeR** [comment]
Same issue, what a shame

**Comment by Ognian** [comment]
I have the same issue;
I found a [fork](https://github.com/Ubun1/mongodb-grafana-backend) with a newer version (0.8.4), but it looks like the same problem
@Ubun1 have you been able to fix this? Or did you just give up?

**Comment by zjesko** [comment]
Any updates on the `Metric request error`?

**Comment by takahiro47** [comment]
Same error...
